databases:
  - name: django_app_db
    databaseName: django_app_db
    user: django_app_user
    region: singapore
    plan: free

services:
  - type: web
    name: django_app
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn todoproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_app_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
